final products = [
  {
    'id': '0',
    'title': 'Airforce J1',
    'type': 'Men running',
    'real price': 44.52,
    'imageUrl': 'assets/images/shoes_1.png',
    'company': 'Nike',
    'sizes': [9, 10, 11, 12],
    'rating': '4.5',
    'disc_price': 43.2,
    'description': 'The Airforce J1 is a versatile running shoe designed for maximum comfort and performance. Its lightweight build ensures easy movement, while the cushioned sole absorbs impact efficiently. Perfect for daily runs and training sessions, this shoe offers durability and style. The breathable material keeps your feet cool and dry, and the sleek design makes it a fashionable choice for both workouts and casual wear.'
  },
  {
    'id': '1',
    'title': 'Ultra Boost',
    'type': 'Women running',
    'real price': 120.99,
    'imageUrl': 'assets/images/shoes_2.png',
    'company': 'Adidas',
    'sizes': [5, 6, 7, 8],
    'rating': '4.8',
    'disc_price': 115.0,
    'description': 'The Ultra Boost running shoes from Adidas are engineered for superior energy return and comfort. Featuring a responsive Boost midsole, these shoes provide exceptional cushioning and support. The Primeknit upper adapts to the changing shape of your foot as you run, ensuring a snug fit. Ideal for both short sprints and long-distance runs, the Ultra Boost combines innovative technology with a stylish design.'
  },
  {
    'id': '2',
    'title': 'Gel-Kayano 27',
    'type': 'Men walking',
    'real price': 160.75,
    'imageUrl': 'assets/images/shoes_3.png',
    'company': 'Asics',
    'sizes': [8, 9, 10, 11],
    'rating': '4.6',
    'disc_price': 150.0,
    'description': 'The Gel-Kayano 27 by Asics is perfect for those who seek stability and comfort in their walking shoes. With a supportive structure and Gel technology cushioning, these shoes reduce the impact on your joints. The breathable upper material ensures ventilation, while the durable outsole provides excellent traction. Suitable for everyday wear, these shoes offer a blend of performance and style.'
  },
  {
    'id': '3',
    'title': 'Air Max 270',
    'type': 'Women casual',
    'real price': 150.00,
    'imageUrl': 'assets/images/shoes_4.png',
    'company': 'Nike',
    'sizes': [6, 7, 8, 9],
    'rating': '4.7',
    'disc_price': 145.0,
    'description': 'The Air Max 270 offers a modern take on the classic Air Max design, featuring the largest Air unit in the heel for a soft and comfortable ride. Its lightweight and breathable upper keep your feet cool, while the snug fit ensures stability. Perfect for casual wear, these shoes deliver a stylish look with unbeatable comfort, making them ideal for everyday use.'
  },
  {
    'id': '4',
    'title': 'Fresh Foam 1080',
    'type': 'Men running',
    'real price': 130.00,
    'imageUrl': 'assets/images/shoes_5.png',
    'company': 'New Balance',
    'sizes': [9, 10, 11, 12],
    'rating': '4.5',
    'disc_price': 125.0,
    'description': 'Experience the ultimate running comfort with the Fresh Foam 1080 by New Balance. These shoes feature a plush Fresh Foam midsole for superior cushioning, while the engineered mesh upper provides a breathable and adaptive fit. The durable outsole offers excellent traction, making these shoes perfect for long-distance running. Stylish and functional, they are a great addition to any runner’s gear.'
  },
  {
    'id': '5',
    'title': 'Speedcross 5',
    'type': 'Women hiking',
    'real price': 140.00,
    'imageUrl': 'assets/images/shoes_6.png',
    'company': 'Salomon',
    'sizes': [5, 6, 7, 8],
    'rating': '4.6',
    'disc_price': 135.0,
    'description': 'The Speedcross 5 by Salomon is a high-performance hiking shoe designed for rugged terrains. Featuring aggressive lugs for better grip and a precise foothold, these shoes provide stability on uneven surfaces. The durable upper and waterproof construction ensure protection against the elements, while the cushioned midsole offers comfort over long hikes. These shoes are ideal for outdoor enthusiasts seeking reliability and performance.'
  },
  {
    'id': '6',
    'title': 'Classic Leather',
    'type': 'Men casual',
    'real price': 80.00,
    'imageUrl': 'assets/images/shoes_7.png',
    'company': 'Reebok',
    'sizes': [8, 9, 10, 11],
    'rating': '4.4',
    'disc_price': 75.0,
    'description': 'Reebok’s Classic Leather shoes offer a timeless design with modern comfort. Crafted from premium leather, these shoes provide durability and a stylish look. The cushioned midsole and padded foam sockliner ensure comfort with every step, making them perfect for everyday wear. The rubber outsole delivers excellent traction and durability, making these shoes a versatile addition to your casual wardrobe.'
  },
  {
    'id': '7',
    'title': 'Chuck Taylor',
    'type': 'Unisex casual',
    'real price': 60.00,
    'imageUrl': 'assets/images/shoes_1.png',
    'company': 'Converse',
    'sizes': [7, 8, 9, 10, 11],
    'rating': '4.3',
    'disc_price': 55.0,
    'description': 'The Chuck Taylor by Converse is an iconic shoe known for its classic design and versatility. Suitable for both men and women, these shoes feature a durable canvas upper and a comfortable rubber sole. The high-top design provides ankle support, while the timeless style makes them a staple in casual fashion. Whether for everyday use or special occasions, the Chuck Taylor is a go-to choice.'
  },
  {
    'id': '8',
    'title': 'Pegasus Trail 2',
    'type': 'Men trail',
    'real price': 130.00,
    'imageUrl': 'assets/images/shoes_3.png',
    'company': 'Nike',
    'sizes': [9, 10, 11, 12],
    'rating': '4.6',
    'disc_price': 125.0,
    'description': 'The Pegasus Trail 2 by Nike is built for trail running, offering a smooth ride on various terrains. With a responsive foam midsole and a durable rubber outsole, these shoes provide excellent traction and stability. The breathable upper keeps your feet cool, while the secure fit ensures confidence on rugged trails. Perfect for trail enthusiasts, these shoes blend performance with comfort.'
  },
  {
    'id': '9',
    'title': 'Wave Rider 24',
    'type': 'Women running',
    'real price': 140.00,
    'imageUrl': 'assets/images/shoes_4.png',
    'company': 'Mizuno',
    'sizes': [5, 6, 7, 8],
    'rating': '4.7',
    'disc_price': 135.0,
    'description': 'Mizuno’s Wave Rider 24 is designed for runners who seek comfort and performance. Featuring Mizuno Wave technology, these shoes provide cushioning and stability. The lightweight design and breathable upper ensure a comfortable fit, while the durable outsole offers excellent traction. Ideal for both short runs and long-distance training, the Wave Rider 24 is a reliable choice for serious runners.'
  },
  {
    'id': '10',
    'title': 'Bondi 7',
    'type': 'Men walking',
    'real price': 150.00,
    'imageUrl': 'assets/images/shoes_5.png',
    'company': 'Hoka One One',
    'sizes': [9, 10, 11, 12],
    'rating': '4.8',
    'disc_price': 145.0,
    'description': 'The Bondi 7 by Hoka One One is a top choice for walkers seeking maximum cushioning. Its full EVA midsole and Meta-Rocker technology provide a smooth and comfortable stride. The breathable upper and plush collar enhance comfort, while the durable outsole ensures longevity. Suitable for long walks and all-day wear, the Bondi 7 combines performance with premium comfort.'
  },
  {
    'id': '11',
    'title': 'Cloud X',
    'type': 'Women running',
    'real price': 140.00,
    'imageUrl': 'assets/images/shoes_6.png',
    'company': 'On Running',
    'sizes': [5, 6, 7, 8],
    'rating': '4.6',
    'disc_price': 135.0,
    'description': 'The Cloud X by On Running is engineered for mixed-sport workouts and running. Featuring Helion superfoam for a responsive ride, these shoes offer exceptional comfort and agility. The lightweight and breathable upper provides a secure fit, while the CloudTec outsole ensures superior cushioning. Ideal for versatile training, the Cloud X blends functionality with a sleek design.'
  },
];
